Add sound null-safety
sarbagyastha/youtube_player_flutter pull request #464
Opened 2021-03-17 14:01 UTC by figengungor

2021-03-22 11:13 UTC, pr-1 commented
@sarbagyastha Any updates on this ?

2021-03-22 11:15 UTC, pr-1 commented on packages/youtube_player_flutter/pubspec.yaml
>    flutter: '>=1.12.13+hotfix.5'
Update this to 
`flutter: '>=2.0.1'`

2021-03-22 11:17 UTC, pr-1 commented on packages/youtube_player_iframe/pubspec.yaml
>    flutter: '>=1.22.0 <2.0.0'
Similarly here 
`flutter: '>2.0.1'`

2021-03-22 11:21 UTC, pr-1 requested changes
Update in pubspec : 
packages/youtube_player_flutter/pubspec.yaml
`flutter : '>2.0.1'`

2021-03-22 12:27 UTC, figengungor commented on packages/youtube_player_flutter/pubspec.yaml
>    flutter: '>=1.12.13+hotfix.5'
Done.

2021-03-22 12:27 UTC, figengungor commented on packages/youtube_player_iframe/pubspec.yaml
>    flutter: '>=1.22.0 <2.0.0'
Done.

2021-03-23 19:23 UTC, pr-1 commented
update version of flutter_inappwebview to latest in pubspec.

2021-03-23 19:34 UTC, pr-1 commented
@figengungor Let me know if you're on it else I will start.

2021-03-23 20:39 UTC, pives commented
i'd love to avoid the gradle update you put in the PR as appcenter isn't compatible with latest. @figengungor

2021-03-24 09:05 UTC, figengungor commented
I fixed dart sdk constraints, updated dependencies which are mistakenly reverted back and downgraded gradle versions.

2021-03-27 01:02 UTC, merged